Fix error that occurs processing fasta files in certain situations. Since the code grabs the first 4 lines of the file, it is possible to end up with two sequence lengths.  "50\n50". The code is expecting a single int value.
Error: ValueError: invalid literal for int() with base 10: '50\n50'